package edu.sinchuk.kurs.views.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.UI;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import edu.sinchuk.kurs.views.OrderInfoView;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class OrderComponent extends HorizontalLayout {
    protected Label title;
    protected Label price;
    protected Button info;

    private String orderTitle;
    private String orderDescription;
    private Integer orderPrice;

    public OrderComponent(String title, String description, Integer price) {
        Design.read(this);

        this.orderTitle = title;
        this.orderDescription = description;
        this.orderPrice = price;

        this.title.setValue("Название: " + title);
        this.price.setValue("Цена: " + String.valueOf(price));

        info.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                UI.getCurrent().getNavigator().addView(OrderInfoView.NAME,
                        new OrderInfoView(orderTitle,orderDescription,orderPrice));
                UI.getCurrent().getNavigator().navigateTo(OrderInfoView.NAME);
            }
        });
    }
}
