alter session set "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER vitaly IDENTIFIED BY q 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "CONNECT" TO vitaly ;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO vitaly ;
GRANT CREATE TABLE TO vitaly ;
GRANT CREATE PROCEDURE TO vitaly ;
GRANT CREATE VIEW TO vitaly ;
GRANT CREATE SESSION TO vitaly ;

-- QUOTAS
ALTER USER vitaly QUOTA 128M ON USERS;

