package edu.sinchuk.kurs.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.UI;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import edu.sinchuk.kurs.models.entities.UserEntity;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DeveloperPanelView extends VerticalLayout implements View {

    final static public String NAME = "user";

    protected Label login;
    protected Button exit;
    protected Button allOrders;
    protected Button editProfile;

    public DeveloperPanelView() {
        Design.read(this);

        login.setValue(((UserEntity) VaadinSession.getCurrent().getAttribute("user")).getUserLogin());

        allOrders.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                UI.getCurrent().getNavigator().addView(MainView.NAME,new MainView());
                UI.getCurrent().getNavigator().navigateTo(MainView.NAME);
            }
        });

        editProfile.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                UI.getCurrent().getNavigator().addView(EditProfileView.NAME,new EditProfileView(NAME));
                UI.getCurrent().getNavigator().navigateTo(EditProfileView.NAME);
            }
        });

        exit.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                UI.getCurrent().getNavigator().addView(LoginView.NAME,new LoginView());
                UI.getCurrent().getNavigator().navigateTo(LoginView.NAME);
            }
        });
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent viewChangeEvent) {
    }
}
