package edu.sinchuk.kurs.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import edu.sinchuk.kurs.models.services.DataBaseConnection;
import edu.sinchuk.kurs.views.components.OrderComponent;
import edu.sinchuk.kurs.views.components.OrdersHeaderComponent;

import java.sql.SQLException;
import java.util.logging.Logger;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainView extends VerticalLayout implements View {

    final static public String NAME = "main";

    private static final Logger logger = Logger.getLogger("MainView");

    protected VerticalLayout orders;
    protected Button myOrders;

    public MainView() {
        addComponent(new OrdersHeaderComponent());
        Design.read(this);

        orders.addComponent(new OrderComponent("Заказ 1","Описание заказа 1",5));
        orders.addComponent(new OrderComponent("Заказ 2","Описание заказа 2",40));
        orders.addComponent(new OrderComponent("Заказ 3","Описание заказа 3",25));
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent viewChangeEvent) {
    }
}
