package edu.sinchuk.kurs.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class OrderInfoView extends FormLayout implements View {

    final static public String NAME = "order";

    protected Label title;
    protected TextArea description;
    protected TextField price;
    protected Button setOrder;
    protected Button write;
    protected Button back;

    public OrderInfoView(String title, String description, Integer price) {
        Design.read(this);

        this.title.setValue(title);
        this.description.setValue(description);
        this.price.setValue(String.valueOf(price));

        back.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                UI.getCurrent().getNavigator().addView(MainView.NAME,new MainView());
                UI.getCurrent().getNavigator().navigateTo(MainView.NAME);
            }
        });
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent viewChangeEvent) {

    }
}
