package edu.sinchuk.kurs.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.data.validator.EmailValidator;
import com.vaadin.data.validator.RegexpValidator;
import com.vaadin.data.validator.StringLengthValidator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Button;
import edu.sinchuk.kurs.controllers.queries.UserQuery;
import edu.sinchuk.kurs.models.services.DataBaseConnection;

import java.sql.SQLException;
import java.util.logging.Logger;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RegisterView extends VerticalLayout implements View {

    final static public String NAME = "register";

    private static final Logger logger = Logger.getLogger("RegisterView");

    protected Label title;
    protected TextField login;
    protected PasswordField pass;
    protected PasswordField passVerf;
    protected TextField name;
    protected TextField lastName;
    protected OptionGroup userType;
    protected Button register;
    protected Button cancel;

    public RegisterView() {
        Design.read(this);

        login.addValidator(new RegexpValidator("^[a-zA-Z][a-zA-Z0-9-_\\.]{1,20}$","Login type error..."));
        pass.addValidator(new StringLengthValidator("Pass type error...",8,20,false));
        passVerf.addValidator(new StringLengthValidator("Pass type error...",8,20,false));
        name.addValidator(new StringLengthValidator("Name type error...",3,20,false));
        lastName.addValidator(new StringLengthValidator("Lastname type error...", 3,20,false));

        register.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                if (pass.getValue() == passVerf.getValue()) {
                    DataBaseConnection connection = new DataBaseConnection();
                    try {
                        UserQuery userQuery = new UserQuery(connection.connect());
                        int groupId = 1;
                        if (userType.isItemEnabled("Developer")) groupId = 2;
                        userQuery.insertUser(login.getValue(), pass.getValue(), name.getValue(), lastName.getValue(), groupId);
                        UI.getCurrent().getNavigator().addView(LoginView.NAME, new LoginView());
                        UI.getCurrent().getNavigator().navigateTo(LoginView.NAME);
                        logger.warning("Подключение установлено!!!");
                    } catch (ClassNotFoundException e) {
                        addComponent(new Label("Ошибка создания пользователя!!!"));
                    } catch (SQLException e) {
                        addComponent(new Label("Ошибка создания пользователя!!!"));
                    }
                } else {
                    addComponent(new Label("Пароли не одинаковы!!!"));
                }
            }
        });

        cancel.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent clickEvent) {
                UI.getCurrent().getNavigator().addView(LoginView.NAME,new LoginView());
                UI.getCurrent().getNavigator().navigateTo(LoginView.NAME);
            }
        });
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent viewChangeEvent) {
    }
}
