-- USER SQL
CREATE USER KURSOVAYA IDENTIFIED BY Bantom274898 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER KURSOVAYA QUOTA 1024000K ON USERS;

-- ROLES
GRANT "CONNECT" TO KURSOVAYA ;
GRANT "RESOURCE" TO KURSOVAYA ;

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO KURSOVAYA ;
GRANT ALTER ANY INDEX TO KURSOVAYA ;
GRANT CREATE TRIGGER TO KURSOVAYA ;
GRANT ALTER ANY PROCEDURE TO KURSOVAYA ;
GRANT CREATE ANY PROCEDURE TO KURSOVAYA ;
GRANT ALTER SESSION TO KURSOVAYA ;
GRANT CREATE MATERIALIZED VIEW TO KURSOVAYA ;
GRANT EXECUTE ANY RULE SET TO KURSOVAYA ;
GRANT DEBUG ANY PROCEDURE TO KURSOVAYA ;
GRANT CREATE ANY SEQUENCE TO KURSOVAYA ;
GRANT CREATE VIEW TO KURSOVAYA ;
GRANT ALTER ANY TABLE TO KURSOVAYA ;
GRANT SELECT ANY TABLE TO KURSOVAYA ;
GRANT FORCE ANY TRANSACTION TO KURSOVAYA ;
GRANT DELETE ANY TABLE TO KURSOVAYA ;
GRANT FLASHBACK ANY TABLE TO KURSOVAYA ;
GRANT BACKUP ANY TABLE TO KURSOVAYA ;
GRANT CREATE TABLE TO KURSOVAYA ;
GRANT DROP ANY TABLE TO KURSOVAYA ;
GRANT EXECUTE ANY CLASS TO KURSOVAYA ;
GRANT CREATE ANY RULE SET TO KURSOVAYA ;
GRANT CREATE TYPE TO KURSOVAYA ;
GRANT SELECT ANY TRANSACTION TO KURSOVAYA ;
GRANT DROP ANY TYPE TO KURSOVAYA ;
GRANT CREATE ANY RULE TO KURSOVAYA ;
GRANT EXECUTE ANY PROCEDURE TO KURSOVAYA ;
GRANT EXECUTE ANY PROGRAM TO KURSOVAYA ;
GRANT EXECUTE ANY TYPE TO KURSOVAYA ;
GRANT DROP ANY INDEX TO KURSOVAYA ;
GRANT ALTER ANY ROLE TO KURSOVAYA ;
GRANT UPDATE ANY TABLE TO KURSOVAYA ;
GRANT DROP ANY VIEW TO KURSOVAYA ;
GRANT EXECUTE ANY RULE TO KURSOVAYA ;
GRANT ALTER ANY TRIGGER TO KURSOVAYA ;
GRANT CREATE ANY VIEW TO KURSOVAYA ;
GRANT EXPORT FULL DATABASE TO KURSOVAYA ;
GRANT COMMENT ANY TABLE TO KURSOVAYA ;
GRANT DROP USER TO KURSOVAYA ;
GRANT CREATE ANY MATERIALIZED VIEW TO KURSOVAYA ;
GRANT FORCE TRANSACTION TO KURSOVAYA ;
GRANT ALTER ANY TYPE TO KURSOVAYA ;
GRANT UNLIMITED TABLESPACE TO KURSOVAYA ;
GRANT CREATE ANY TRIGGER TO KURSOVAYA ;
GRANT CREATE ANY TABLE TO KURSOVAYA ;
GRANT CREATE ANY TYPE TO KURSOVAYA ;
GRANT ALTER DATABASE TO KURSOVAYA ;
GRANT ALTER ANY RULE TO KURSOVAYA ;
