INSERT INTO "MNKACH"."TEACHERS" (T_PHONE_NUMBER, T_NAME, T_SURNAME, T_PASSWORD, T_EMAIL, T_IS_ACTIVE) VALUES ('0672863422', 'Петро', 'Петрович', 'йцукенгшщ', 'petrovich@ukr.net', '1')
INSERT INTO "MNKACH"."TEACHERS" (T_PHONE_NUMBER, T_NAME, T_SURNAME, T_PASSWORD, T_EMAIL, T_IS_ACTIVE) VALUES ('0974513456', 'Василь', 'Жайворон', 'кверті123', 'zhaivoron@ukr.net', '1')

INSERT INTO "MNKACH"."ROOMS" (R_NUMBER, R_BUILD_NUMBER) VALUES ('97', '15')
INSERT INTO "MNKACH"."ROOMS" (R_NUMBER, R_BUILD_NUMBER) VALUES ('93', '15')
INSERT INTO "MNKACH"."ROOMS" (R_NUMBER, R_BUILD_NUMBER) VALUES ('95', '15')

INSERT INTO "MNKACH"."SUBJECTS" (SUBJ_NAME, SUBJ_CREDITS) VALUES ('Математика', '3')
INSERT INTO "MNKACH"."SUBJECTS" (SUBJ_NAME, SUBJ_CREDITS) VALUES ('Біологія', '0.5')

INSERT INTO "MNKACH"."STUDENTS" (S_PHONE_NUMBER, S_NAME, S_SURNAME, S_PASSWORD, S_EMAIL, S_GROUP, S_IS_ACTIVE) VALUES ('0732563785', 'Василина', 'Іванів', 'красуня785', 'ivvaska@gmail.com', 'КМ-34', '1')

INSERT INTO "MNKACH"."SCHEDULE" (T_EMAIL_FK, SUBJ_NAME_FK, SCH_DATE, R_NUMBER_FK, R_BUILD_NUMBER_FK) VALUES ('petrovich@ukr.net', 'Математика', TO_DATE('24.12.2016', 'DD.MM.RRRR'), '97', '15')
INSERT INTO "MNKACH"."ATTENDANCE" (T_EMAIL_FK, S_EMAIL_FK, SUBJ_NAME_FK, SCH_DATE_FK, ATT_PRESENCE) VALUES ('petrovich@ukr.net', 'ivvaska@gmail.com', 'Математика', TO_DATE('24.12.2016', 'DD.MM.RRRR'), '1')
