CREATE TABLE QUESTIONS
(
  QUEST_NUM      NUMBER  NOT NULL PRIMARY KEY,
  QUEST_TEXT    char(10)  NOT NULL ,
  QUEST_STATUS  NUMBER NOT NULL
);
INSERT INTO QUESTIONS (QUEST_NUM,  QUEST_TEXT, QUEST_STATUS)
VALUES (1, 'first question', 1);


CREATE TABLE ANSWERS
(
  QUEST_NUM      NUMBER  NOT NULL,
  ANSWER_VARIANT char(1)  NOT NULL ,
  ANSWER_TEXT char(10) NOT NULL,
  ANSWER_CORRECT NUMBER NOT NULL,
  ANSWER_STATUS NUMBER NOT NULL
);

CREATE TABLE organisms
(
  organism_box      char(32)  NOT NULL PRIMARY KEY,
  organism_code     char(32)  NOT NULL,
  organism_title    char(12)  NOT NULL ,
  organism_secondTitle  char(12)  NOT NULL,
  organism_god      NUMBER NOT NULL
);
-----------------------------
CREATE TABLE Tests
(
  ORGANISM_BOX char(32)  NOT NULL,
  Test_date    date  NOT NULL,
  QUEST_NUM      NUMBER  NOT NULL,
  Test_answer   NUMBER NOT NULL
);

ALTER TABLE Tests ADD CONSTRAINT 
PK_Tests PRIMARY KEY 
(ORGANISM_BOX,Test_date,QUEST_NUM);

ALTER TABLE Tests 
ADD CONSTRAINT FK_Tests_Organisms_box FOREIGN KEY (ORGANISM_BOX) REFERENCES ORGANISMS (ORGANISM_BOX);

ALTER TABLE Tests 
ADD CONSTRAINT FK_Tests_Questions_num FOREIGN KEY (QUEST_NUM) REFERENCES Questions (QUEST_NUM);

-------------------------------------------------

CREATE TABLE IQ
(
  ORGANISM_BOX char(32)  NOT NULL,
  Test_date    date  NOT NULL,
  iq_level      NUMBER  NOT NULL
);

ALTER TABLE IQ ADD CONSTRAINT 
PK_IQ PRIMARY KEY 
(ORGANISM_BOX,Test_date);

ALTER TABLE IQ 
ADD CONSTRAINT FK_IQ_ORGANISMS_box FOREIGN KEY (ORGANISM_BOX) REFERENCES ORGANISMS (ORGANISM_BOX);

------------------------

---------------------

ALTER TABLE ANSWERS ADD CONSTRAINT 
PK_Answer PRIMARY KEY 
(QUEST_NUM, ANSWER_VARIANT );

ALTER TABLE ANSWERS 
ADD CONSTRAINT FK_Answers_Questions FOREIGN KEY (QUEST_NUM) REFERENCES QUESTIONS (QUEST_NUM);

--

CREATE VIEW availableQuestions AS
SELECT QUEST_NUM+9 AS QNUM, QUEST_TEXT AS QTEXT from QUESTIONS
WHERE QUEST_STATUS=1
ORDER by QUEST_NUM+9;

--

CREATE VIEW availableAnswers AS
SELECT QUESTIONS.QUEST_NUM+9 AS QNUM, QUEST_TEXT AS QTEXT,ANSWER_VARIANT AS AVARIANT,  ANSWER_TEXT AS ATEXT, ANSWER_CORRECT AS ACORRECT 
from ANSWERS inner JOIN QUESTIONS on ANSWERS.QUEST_NUM = QUESTIONS.QUEST_NUM
WHERE ANSWER_STATUS=1
ORDER by QUESTIONS.QUEST_NUM+9, ANSWER_VARIANT;

--

CREATE VIEW users AS
SELECT organism_box AS mail, organism_code AS userpassword, 
organism_title AS username,organism_god AS adminstatus
from ORGANISMS;





