--------------------------------------------------------
--  File created - Sunday-December-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KPI"."BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 500 START WITH 500 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence HOTEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KPI"."HOTEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 500 START WITH 500 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ROOM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KPI"."ROOM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 500 START WITH 500 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table BOOKINGS
--------------------------------------------------------

  CREATE TABLE "KPI"."BOOKINGS" 
   (	"BOOKING_ID" NUMBER(10,0), 
	"BOOKING_DATE_IN" DATE, 
	"BOOKING_DATE_OUT" DATE, 
	"BOOKING_ROOM" NUMBER, 
	"BOOKING_CUSTOMER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "KPI"."CUSTOMERS" 
   (	"CUST_EMAIL" VARCHAR2(20 BYTE), 
	"CUST_NAME" VARCHAR2(40 BYTE), 
	"CUST_COUNTRY" VARCHAR2(20 BYTE), 
	"CUST_PHONE" VARCHAR2(20 BYTE), 
	"CUST_PASS" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOTELS
--------------------------------------------------------

  CREATE TABLE "KPI"."HOTELS" 
   (	"HOTEL_ID" NUMBER(10,0), 
	"HOTEL_DESCRIPTION" VARCHAR2(20 BYTE), 
	"HOTEL_NAME" VARCHAR2(20 BYTE), 
	"HOTEL_ADDRESS" VARCHAR2(20 BYTE), 
	"HOTEL_OWNER" VARCHAR2(20 BYTE), 
	"HOTEL_CITY" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OWNERS
--------------------------------------------------------

  CREATE TABLE "KPI"."OWNERS" 
   (	"OWNER_EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOMS
--------------------------------------------------------

  CREATE TABLE "KPI"."ROOMS" 
   (	"ROOM_ID" NUMBER(10,0), 
	"ROOM_CAPACITY" NUMBER(10,0), 
	"ROOM_DESCRIPTION" VARCHAR2(50 BYTE), 
	"ROOM_HOTEL" NUMBER(10,0), 
	"ROOM_PRICE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KPI.BOOKINGS
SET DEFINE OFF;
Insert into KPI.BOOKINGS (BOOKING_ID,BOOKING_DATE_IN,BOOKING_DATE_OUT,BOOKING_ROOM,BOOKING_CUSTOMER) values (1,to_date('27-DEC-16','DD-MON-RR'),to_date('28-DEC-16','DD-MON-RR'),1,'n@gmail.com');
REM INSERTING into KPI.CUSTOMERS
SET DEFINE OFF;
Insert into KPI.CUSTOMERS (CUST_EMAIL,CUST_NAME,CUST_COUNTRY,CUST_PHONE,CUST_PASS) values ('a@gmail.com','Nick',null,null,'devildevil');
Insert into KPI.CUSTOMERS (CUST_EMAIL,CUST_NAME,CUST_COUNTRY,CUST_PHONE,CUST_PASS) values ('n@gmail.com','nazar',null,null,'12345');
REM INSERTING into KPI.HOTELS
SET DEFINE OFF;
Insert into KPI.HOTELS (HOTEL_ID,HOTEL_DESCRIPTION,HOTEL_NAME,HOTEL_ADDRESS,HOTEL_OWNER,HOTEL_CITY) values (1,'something','Glory','ul. Pawla','a@gmail.com','Krakow');
Insert into KPI.HOTELS (HOTEL_ID,HOTEL_DESCRIPTION,HOTEL_NAME,HOTEL_ADDRESS,HOTEL_OWNER,HOTEL_CITY) values (2,'Fabolous','Victory','ul. Dekerta','a@gmail.com','Krakow');
Insert into KPI.HOTELS (HOTEL_ID,HOTEL_DESCRIPTION,HOTEL_NAME,HOTEL_ADDRESS,HOTEL_OWNER,HOTEL_CITY) values (3,'Great','Papa','ul. Rota','a@gmail.com','Krakow');
REM INSERTING into KPI.OWNERS
SET DEFINE OFF;
Insert into KPI.OWNERS (OWNER_EMAIL) values ('a@gmail.com');
REM INSERTING into KPI.ROOMS
SET DEFINE OFF;
Insert into KPI.ROOMS (ROOM_ID,ROOM_CAPACITY,ROOM_DESCRIPTION,ROOM_HOTEL,ROOM_PRICE) values (1,2,'perfect',1,99);
Insert into KPI.ROOMS (ROOM_ID,ROOM_CAPACITY,ROOM_DESCRIPTION,ROOM_HOTEL,ROOM_PRICE) values (2,3,'funny',1,78);
Insert into KPI.ROOMS (ROOM_ID,ROOM_CAPACITY,ROOM_DESCRIPTION,ROOM_HOTEL,ROOM_PRICE) values (3,1,'bad',2,55);
--------------------------------------------------------
--  DDL for Index HOTEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KPI"."HOTEL_PK" ON "KPI"."HOTELS" ("HOTEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOOKINGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KPI"."BOOKINGS_PK" ON "KPI"."BOOKINGS" ("BOOKING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROOMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KPI"."ROOMS_PK" ON "KPI"."ROOMS" ("ROOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KPI"."CUSTOMERS_PK" ON "KPI"."CUSTOMERS" ("CUST_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OWNERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KPI"."OWNERS_PK" ON "KPI"."OWNERS" ("OWNER_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOKINGS
--------------------------------------------------------

  ALTER TABLE "KPI"."BOOKINGS" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "KPI"."BOOKINGS" MODIFY ("BOOKING_DATE_IN" NOT NULL ENABLE);
  ALTER TABLE "KPI"."BOOKINGS" MODIFY ("BOOKING_DATE_OUT" NOT NULL ENABLE);
  ALTER TABLE "KPI"."BOOKINGS" MODIFY ("BOOKING_ROOM" NOT NULL ENABLE);
  ALTER TABLE "KPI"."BOOKINGS" MODIFY ("BOOKING_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "KPI"."BOOKINGS" ADD CONSTRAINT "BOOKINGS_PK" PRIMARY KEY ("BOOKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOTELS
--------------------------------------------------------

  ALTER TABLE "KPI"."HOTELS" MODIFY ("HOTEL_ID" NOT NULL ENABLE);
  ALTER TABLE "KPI"."HOTELS" MODIFY ("HOTEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "KPI"."HOTELS" MODIFY ("HOTEL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "KPI"."HOTELS" MODIFY ("HOTEL_OWNER" NOT NULL ENABLE);
  ALTER TABLE "KPI"."HOTELS" ADD CONSTRAINT "HOTEL_PK" PRIMARY KEY ("HOTEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KPI"."HOTELS" MODIFY ("HOTEL_CITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "KPI"."CUSTOMERS" MODIFY ("CUST_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KPI"."CUSTOMERS" MODIFY ("CUST_NAME" NOT NULL ENABLE);
  ALTER TABLE "KPI"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUST_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KPI"."CUSTOMERS" MODIFY ("CUST_PASS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OWNERS
--------------------------------------------------------

  ALTER TABLE "KPI"."OWNERS" MODIFY ("OWNER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KPI"."OWNERS" ADD CONSTRAINT "OWNERS_PK" PRIMARY KEY ("OWNER_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROOMS
--------------------------------------------------------

  ALTER TABLE "KPI"."ROOMS" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "KPI"."ROOMS" MODIFY ("ROOM_CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "KPI"."ROOMS" MODIFY ("ROOM_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "KPI"."ROOMS" MODIFY ("ROOM_HOTEL" NOT NULL ENABLE);
  ALTER TABLE "KPI"."ROOMS" ADD CONSTRAINT "ROOMS_PK" PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KPI"."ROOMS" MODIFY ("ROOM_PRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOKINGS
--------------------------------------------------------

  ALTER TABLE "KPI"."BOOKINGS" ADD CONSTRAINT "BOOKINGS_FK1" FOREIGN KEY ("BOOKING_ROOM")
	  REFERENCES "KPI"."ROOMS" ("ROOM_ID") ENABLE;
  ALTER TABLE "KPI"."BOOKINGS" ADD CONSTRAINT "BOOKINGS_FK2" FOREIGN KEY ("BOOKING_CUSTOMER")
	  REFERENCES "KPI"."CUSTOMERS" ("CUST_EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOTELS
--------------------------------------------------------

  ALTER TABLE "KPI"."HOTELS" ADD CONSTRAINT "HOTEL_FK" FOREIGN KEY ("HOTEL_OWNER")
	  REFERENCES "KPI"."OWNERS" ("OWNER_EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OWNERS
--------------------------------------------------------

  ALTER TABLE "KPI"."OWNERS" ADD CONSTRAINT "OWNERS_FK" FOREIGN KEY ("OWNER_EMAIL")
	  REFERENCES "KPI"."CUSTOMERS" ("CUST_EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROOMS
--------------------------------------------------------

  ALTER TABLE "KPI"."ROOMS" ADD CONSTRAINT "ROOMS_FK" FOREIGN KEY ("ROOM_HOTEL")
	  REFERENCES "KPI"."HOTELS" ("HOTEL_ID") ENABLE;
